# Generated by Django 3.2.6 on 2024-03-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_usercheckpoint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckpoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercheckpoint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.user'),
        ),
    ]
